# Generated by Django 4.2.27 on 2026-01-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique Employee ID', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Full Name', max_length=100)),
                ('email', models.EmailField(help_text='Email Address (must be valid format)', max_length=254)),
                ('department', models.CharField(help_text='Department', max_length=100)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], help_text='Status: Present or Absent', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
